services:
  # 1. Nginx Proxy
  proxy-server:
    build: ./nginx
    container_name: pqc-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/opt/nginx/nginx-conf/nginx.conf
    depends_on:
      - backend-api
    networks:
      - pqc-network

  # 2. 백엔드 (FastAPI Backend)
  backend-api:
    build: ./backend
    container_name: service-backend
    volumes:
      - ./backend:/app
    environment:
      - ENV=development
    networks:
      - pqc-network

  # 3. 테스터 (Kali Linux)
  test-client:
    build: ./tester
    container_name: tls-tester
    volumes:
      - ./tester/captures:/data
    command: tail -f /dev/null
    networks:
      - pqc-network

networks:
  pqc-network:
    driver: bridge