services:
  proxy-server:
    build: ./nginx
    container_name: pqc-proxy-prod
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      - TLS_STAGE=${TLS_STAGE:-1}
    depends_on:
      - backend-api
    networks:
      - pqc-network

  backend-api:
    build: ./backend
    container_name: service-backend-prod
    restart: always
    environment:
      - ENV=production
    networks:
      - pqc-network

  test-client:
    build: ./tester
    container_name: tls-tester-prod
    restart: on-failure
    command: tail -f /dev/null
    networks:
      - pqc-network

networks:
  pqc-network:
    driver: bridge