events {}

http {
    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate     /home/yulimH/quantum-jump/pqc-webserver/certs/server.crt;
        ssl_certificate_key /home/yulimH/quantum-jump/pqc-webserver/certs/server.key;

        ssl_protocols TLSv1.3;
        ssl_ecdh_curve p521_mlkem1024:p384_mlkem768;
        ssl_prefer_server_ciphers on;

        location / {
            return 200 "Stage 3: Post-Quantum TLS (실험적)\n";
            add_header Content-Type text/plain;
        }
    }
}
